name: Moonrootsproject
favicon: null
layout_spectrum: 0.14329
typography_spectrum: 0.49241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a032c'
    - '#ffffff'
    - '#c1bb97'
    - '#7d6690'
    - '#f706e9'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
