name: Moonrootsproject
favicon: null
layout_spectrum: 0.072046990506351
typography_spectrum: 0.39969393354840577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5320749264210463
  lightness: 0.6991766723804176
  saturation: 0.13609866797924042
  rhythmicContrast: 0.024889812106266618
purpose: []
