name: Moonrootsproject
favicon: null
layout_spectrum: 0.14329
typography_spectrum: 0.49241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3125
  lightness: 0.6991766723804176
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
