name: Moonrootsproject
favicon: null
layout_spectrum: 0.49428
typography_spectrum: 0.71517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192936'
    - '#d0e0b1'
    - '#51af97'
    - '#b0ac51'
    - '#737e46'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
